name: Sonar
on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types: 
      - completed
  workflow_dispatch:
    inputs:
      prKey:
        description: 'PR Key'     
        required: true
      prBranch:
        description: 'PR Branch'     
        required: true
      prBase:
        description: 'PR Base Branch'     
        required: true
        default: master
jobs:
  sonar:
    name: Sonar
    runs-on: ubuntu-latest
    # if: github.event.workflow_run.conclusion == 'success'
    env:
     PR_KEY: ${{ github.event.workflow_run.pull_requests[0].number }} 
    steps:  
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          ref: ${{ github.event.workflow_run.head_branch }}
          fetch-depth: 0
      - name: Upload Sonar report to sonarcloud.io and comment in pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          BRANCH_NAME: ${{ github.event.workflow_run.head_branch }}
        run: |
          mvn -B verify sonar:sonar -Dsonar.coverage.jacoco.xmlReportPaths=../core/target/site/jacoco/jacoco.xml -Dsonar.organization=adobeinc -Dsonar.projectKey=adobe_aem-spa-project-core -Dsonar.login=$SONAR_TOKEN -Dsonar.pullrequest.key=${{ github.event.inputs.prKey }} -Dsonar.pullrequest.branch=${{ github.event.inputs.prBranch }} -Dsonar.pullrequest.base=${{ github.event.inputs.prBase }}
          echo "$BRANCH_NAME"
          echo ${{ github.event.workflow_run.head_sha }}
          echo "PR_KEY"


